"""Run Lab 2 experiments."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
LIB_SRC = ROOT / "optimlib" / "src"
for path in (LIB_SRC, ROOT):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import optimlib  # noqa: F401,E402
import lab2.functions  # noqa: F401,E402
from optimlib.experiment.runner import OptimizationExperiment
from optimlib.utils.registry import GLOBAL_REGISTRY
from optimlib.visualization.contour import plot_contours_and_trajectories
from optimlib.visualization.convergence import plot_convergence
from optimlib.visualization.lab2 import (
    plot_lab2_ackley_trajectories,
    plot_lab2_constant_step_alpha,
    plot_lab2_tolerance_dependencies,
    save_lab2_complex_summary_table,
)


def _variant_basename(function_name: str, function_params: dict[str, Any]) -> str:
    """Filesystem-safe basename for a function instance (e.g. different x0)."""
    if not function_params:
        return function_name
    compact = json.dumps(function_params, sort_keys=True, separators=(",", ":"))
    safe = re.sub(r"[^0-9A-Za-z_.-]+", "_", compact)
    return f"{function_name}_{safe}"


def _latex_escape(value: object) -> str:
    text = "" if value is None else str(value)
    if text == "nan":
        return ""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _format_table_value(value: object) -> str:
    if isinstance(value, float):
        if value != value:
            return ""
        return f"{value:.4g}"
    if isinstance(value, list | dict):
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return "" if value is None else str(value)


def _save_summary_report_table(experiment: OptimizationExperiment, chunk_size: int = 34) -> Path:
    """Save a compact LaTeX summary table used by Report_demo2.tex."""
    dataframe = experiment.to_dataframe()
    columns = [
        "function",
        "function_params",
        "optimizer",
        "tolerance",
        "params",
        "converged",
        "f",
        "n_iter",
        "n_calls",
        "n_grad_calls",
    ]
    headers = ["function", "f.params", "optimizer", "tol", "params", "conv.", "f", "iter", "calls", "grad"]
    output_path = experiment.config.output_dir / "summary_report_scaled.tex"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% Auto-generated by lab2/run.py",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.05}",
    ]
    for start in range(0, len(dataframe), chunk_size):
        chunk = dataframe.iloc[start : start + chunk_size]
        lines.extend(
            [
                r"\fitreporttable{%",
                r"\begin{tabular}{llllllllll}",
                r"\toprule",
                " & ".join(_latex_escape(header) for header in headers) + r" \\",
                r"\midrule",
            ]
        )
        for _, row in chunk.iterrows():
            values = [_latex_escape(_format_table_value(row.get(column))) for column in columns]
            lines.append(" & ".join(values) + r" \\")
        lines.extend(
            [
                r"\bottomrule",
                r"\end{tabular}%",
                r"}",
                "",
            ]
        )
    lines.append(r"\endgroup")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def main() -> None:
    """Execute Lab 2 and save tables and plots."""
    experiment = OptimizationExperiment.from_yaml(Path(__file__).with_name("config.yaml"))
    traj_tol = float(experiment.config.plots.get("trajectory_tolerance", 1e-8))
    runs = experiment.execute()
    plot_dir = experiment.config.output_dir / "plots"
    for function_config in experiment.config.normalized_functions():
        func = GLOBAL_REGISTRY.get_function(function_config.name, **function_config.params)
        fparams = dict(function_config.params)
        selected = [
            run
            for run in runs
            if run.function_name == function_config.name
            and run.function_params == fparams
            and run.result is not None
            and abs(run.tolerance - traj_tol) <= 1e-12 * max(1.0, abs(traj_tol))
        ]
        stem = _variant_basename(function_config.name, fparams)
        plot_contours_and_trajectories(func, selected, plot_dir, f"{stem}_trajectories")
        plot_convergence(selected, plot_dir, f"{stem}_convergence", f_min=float(func.f_min or 0.0))
        if function_config.name == "Ackley" and fparams == {"x0": [-2.0, -2.0]}:
            plot_lab2_ackley_trajectories(func, runs, plot_dir, tolerance=traj_tol)
    plot_lab2_constant_step_alpha(runs, plot_dir, tolerance=traj_tol)
    plot_lab2_tolerance_dependencies(runs, plot_dir)
    print(f"Lab 2 completed: {len(runs)} runs")
    table_paths = experiment.save_tables()
    table_paths["complex_summary"] = save_lab2_complex_summary_table(runs, experiment.config.output_dir / "tables", tolerance=traj_tol)
    for name, path in table_paths.items():
        print(f"{name}: {path}")


if __name__ == "__main__":
    main()
